// This is to before adding, removing product we have verify that token that is admin we will check that
// by checking the token would have generated by the admin login(It would be static no change)
// That token would be passed as header in frontend later

import jwt from 'jsonwebtoken';

const adminAuth = async(req,res,next) => {
try {
    const {token} = req.headers;
    if(!token){
       return res.json({success: false, message: "Not Authorized login again"})
    }
    const token_decode = jwt.verify(token, process.env.JSON_SECRET);

    if(token_decode !== process.env.ADMIN_EMAIL + process.env.ADMIN_PASSWORD){
      return  res.json({success: false, message: "Not Authorized login again"})
    }

    next();
} catch (error) {
    console.log(error);
    res.json({success: false, message: error.message})
}
   
}

export default adminAuth;

